aliases:
  - &install-dependencies
    name: Install dependencies
    command: |
      apk add --update --no-cache nodejs nodejs-npm python3 make g++ pkgconfig libsecret-dev
      npm config set unsafe-perm true
      npm i -g npm
      node --version
      npm --version
      npm install

version: 2
jobs:
  release_production:
    working_directory: /app
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: *install-dependencies
      - run:
          name: Release Production Image
          command: |
            set +o pipefail
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker build --no-cache -t motionbank/users-api:latest .
            docker push motionbank/users-api:latest

workflows:
  version: 2
  build_pipeline:
    jobs:
      - release_production:
          filters:
            branches:
              only: master
